### PR TITLE
add Deprecating the Observer Pattern by Maier, Rompf & Odersky

### PR DESCRIPTION
**Pull request by acjay**
Excellent and instructive paper on how to migrate from callback-style event-driven architecture to a model that uses representations of data streams as first-class values. This results in composability and cleaner control flow, among other benefits explained in the paper.

### CODE REVIEW

**Comment by NewAlexandria** [comment]
What is the copyright of this paper?

**Comment by acjay** [comment]
That's a good question, I don't know. Maybe @odersky can clarify whether it can be republished here?

**Comment by DarrenN** [comment]
This paper seems well within the public domain: https://duckduckgo.com/?q=EPFL-REPORT-148043

@zeeshanlakhani / @hakutsuru - care to make a call?

**Comment by odersky** [comment]
On Fri, Sep 4, 2015 at 7:51 PM, Alan Johnson <notifications@github.com>
wrote:

> That's a good question, I don't know. Maybe @odersky
> <https://github.com/odersky> can clarify whether it can be republished
> here?
>
Yes, please include it.

 - Martin

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/papers-we-love/papers-we-love/pull/330#issuecomment-137804733>
> .
>



-- 
Martin Odersky
EPFL and Typesafe

**Comment by DarrenN** [comment]
Thanks @odersky !

**Pull request merged**
