### PR TITLE
Added Complexity section with Stephen Cook paper

### PR DESCRIPTION
**Pull request by JKereliuk**

### CODE REVIEW

**Comment by DarrenN** [comment]
Wouldn't this go under Program Verification https://github.com/papers-we-love/papers-we-love/tree/c248ded17ef03750bb342d0e0e3ce6f96297d6d4/program_verification as it concerns theorem proving or am I misunderstanding the paper?

**Comment by zeeshanlakhani** [comment]
@JKereliuk thoughts on moving this to Program Verification?

**Comment by DarrenN** [comment]
Going to close due to inactivity soon.

**Comment by DarrenN** [comment]
Closed due to inactivity. Please re-open once the outstanding issues are addressed.

**Pull request closed without merging**
