### PR TITLE
Added gravity paper

### PR DESCRIPTION
**Pull request by dierhotusx**
## Paper Title:
Experimental Research of the Magnetic-Gravity Effects. Full Size SEG tests.

### Paper Year:
1998

### Reasons for including paper:
- Addresses one of the holy grail of physics - control gravity.
- An experimental setup that demos magnetic-gravity interaction.
- IF this is TRUE, then it will fully elevate transport system from ground to sky.

### CODE REVIEW

**Comment by DarrenN** [comment]
@dierhotusx thanks for the PR! Please add an entry for the paper to the README in the `physics` folder:

https://github.com/papers-we-love/papers-we-love/tree/master/physics

**Comment by deltamualpha** [comment]
This doesn't feel like a great fit for the repo. There's no computer science connection, and it's not a classic paper like, say [On The Electrodynamics of Moving Bodies](https://github.com/papers-we-love/papers-we-love/blob/master/physics/on-the-electrodynamics-of-moving-bodies.pdf). Also, SEG machines are sort of... crank-y?

**Comment by NewAlexandria** [comment]
I have read lots in this area, as the fringe edges of thinking and research is a great wellspring, so I feel I should chime in.  There is really a 'repo policy' level question here for @zeeshanlakhani and others. This PR introduces a paper that performed a basic study of a Searl device.  Searl devices ('motors') are controversial in their operation, like Bedini motors.  They (both) may demonstrate something anomalous to classical assumptions / textbooks, and a great research topic for hobbyists — since 'win or lose', one learns lots when buildings these kits. That said, the controversial nature of this research often drives people away from discussing the topic.

I think this is a worthwhile paper, within that spectrum of research.

**Comment by DarrenN** [comment]
We've discussed internally. Going to close this for now, but, would be open to discuss creating a folder for more experimental hardware related type papers that carry some more explanatory around them. Feel free to re-open if you'd like to make a move in that direction.

**Comment by dierhotusx** [comment]
ohhh, seems I missed the whole discussion.
shall I want it to be merged? I think smart, critical minds shall evaluate experimental also outside the mainroad. Is there some cultural part I am missing to which I have to comply, because this is good paper. Is like one about aerodynamics in early 1900s. Everything on the topic is evaluated to be  to be "crank-y", until one builds and flies it.
For that argument, I feel it is important to explore the unknown. Of course it is fun to explore "the known" and "the weird", "the funny" etc., but only and only when we look beyond the borders of our classic material we get an opportunity to find new horizons.
@DarrenN @deltamualpha @NewAlexandria 

@DarrenN I can add README in physics folder, happy to do that.

**Comment by DarrenN** [comment]
Hi @dierhotusx 

> shall I want it to be merged? is it a "must" precondition for presenting in PapesWeLove?

No, a paper does not have to be in the repo to be presented at a Papers We Love meetup. In fact there are many papers we cannot host because of licensing restrictions (ACM, Springer, IEEE, etc.)

As mentioned in my comment on 12/15, I think we're okay with merging this paper if its moved to a folder such as "Experimental Hardware" or "Theoretical Physics" and has a clear README attached.

**Comment by dierhotusx** [comment]
Perfect!
I will make the ^ happen as soon as done with traveling, ETA by end of the week.

**Pull request closed without merging**
