### PR TITLE
ADD J. P. Grossman | march-13-2002 | hw | systolic array LRU

### PR DESCRIPTION
**Pull request by alphazero**
#### Reasons for including paper

A short and focused paper -- appropriately self described as a technical memo of the Aries (Advanced RAM Integration for Efficiency and Scalability) project -- presents a very interesting take on LRU management. While directly not applicable in the software domain, the systolic array mechanism presented in this paper is quite interesting and afaik quite novel.

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
Thank you for this @alphazero! Mind adding a item in the topic README for the paper and use :scroll: cause we host it? For more info: https://github.com/papers-we-love/papers-we-love/blob/master/.github/CONTRIBUTING.md#follow-our-commit-naming-and-directory-organization-conventions.

**Comment by alphazero** [comment]
Have sent email to author asking for copyright clarification. We'll follow up on this if he replies or I timeout on non-reply.

**Comment by alphazero** [comment]
@zeeshanlakhani Mr. Grossman apparently keeps a very low profile & email to his MIT coordinates bounce. Per your reading of the paper (which merely mentions DARPA) is this something you can host directly or would you prefer PR is modified to simply points to [original url](http://www.ai.mit.edu/projects/aries/Documents/Memos/ARIES-18.pdf).

**Comment by zeeshanlakhani** [comment]
@alphazero let's modify this to point to the original url. Mind doing that and rebasing into 1 commit? Thanks.

**Comment by alphazero** [comment]
Go ahead and do so on your end. I zapped my clone at some point between March 15 and June 2016.

**Pull request closed without merging**
