### PR TITLE
Adding the simple economics of open source paper

### PR DESCRIPTION
**Pull request by Khalian**
### Reasons for including paper : A good understanding of the incentives as to why developers contribute to open source and an analysis of the same. 

-
-
-

### CODE REVIEW

**Comment by hakutsuru** [comment]
Please add a new category on the page for the item you are adding, e.g. update your changes to be...

```
## Open Source

* [The Simple economics of Open Source  (2000)] (http://www.people.hbs.edu/jlerner/simple.pdf) by Josh Lerner and Jean Tirole
```

(If I am not handling this the best way, let me know. Most of my github work has been with private repos. Thanks.)

**Comment by Khalian** [comment]
@hakutsuru 

I dont really think its an open source paper. Its an economic analysis.

**Comment by hakutsuru** [comment]
You added a paper under this section...
```
# Economics

## Auctions and Bidding
```

Is the paper about "Auctions and Bidding"?

Would you like me to handle this update for you?

**Comment by Khalian** [comment]
Ok done.

**Comment by hakutsuru** [comment]
I appreciate this @Khalian. @zeeshanlakhani and I agree we should put more thought into organizing some of these topics... Hopefully soon!

**Pull request merged**
