### PR TITLE
Added Winnipeg

### PR DESCRIPTION
**Pull request by mogigoma**
Added a link for the chapter in Winnipeg, Manitoba, Canada. We have several universities and a large hackerspace in town, about time we made a chapter of our own!

### CODE REVIEW

**Comment by DarrenN** [comment]
Hi @mogigoma - let us know once you've had your first meetup and we will merge this in. Thanks!

**Comment by mogigoma** [comment]
Took a while, but we have had our first meetup!

**Comment by zeeshanlakhani** [comment]
@mogigoma can you update this PR w/ master and then we'll merge it. Great to hear!

**Comment by zeeshanlakhani** [comment]
Also, @mogigoma, what's a good email to reach you at? I'll add you to our Google Admin Group and give you access to upload the videos to our YouTube channel :).

**Comment by mogigoma** [comment]
@zeeshanlakhani PR updated. My email is mak.kolybabi at gmail, thanks!

**Comment by zeeshanlakhani** [comment]
:+1:

**Comment by makkolybabiobs** [comment]
Thanks!

**Pull request merged**
