### PR TITLE
Adding Hardware Security as a new sub-research area

### PR DESCRIPTION
**Pull request by FaresSalem**
### Reasons for including paper
- A really interesting paper that's written very well and easy to read and understand

### CODE REVIEW

**Comment by hakutsuru** [comment]
Please change this to not introduce the `hardware_security` subfolder?

Preferable to use subsections of the top-level readme until there is enough variety and content to justify further complexity.

Your breakdown is fine, just in the top readme...
```
Security
====

## Software Security
[...]

## Hardware Security
[...]
```

If another organizer thinks this is ready, I would not block merging. But I would rather not reorganize this topic yet.

**Comment by jmarkinman** [comment]
Be careful with this one guys, Anyone who practices this is subject.

**Comment by FaresSalem** [comment]
I've made the edits which seem more logical for the current number of security papers, Maybe for future updates we'll need to rearrange the Binary files to sub-folders as well.

**Comment by hakutsuru** [comment]
Thank you, @FaresSalem

**Pull request merged**
