### PR TITLE
Math papers from original `isomorphisms` PR

### PR DESCRIPTION
**Pull request by NewAlexandria**
## Paper Title:

These are all the `Mathematics` and `Machine Learning` papers that were submitted in https://github.com/papers-we-love/papers-we-love/pull/550

### Reasons for including paper

Good papers and nice commentaries.  I've made changes relative to the PR discussion.

----

This should be good now, but would appreciate a second pair of eyes before merging.

### CODE REVIEW

**Comment by NewAlexandria** [comment]
@hakutsuru @DarrenN

**Comment by hakutsuru** [comment]
The requests by @DarrenN were the minimal changes for this material to be included. Since it was not clear anyone would undertake this work, we left other obvious issues unstated.

If you are now championing this, we will get it done, but it may take a bit more work.

****

I will review included PDFs for copyright issues soon. Every included PDF must be free of copyright issues, properly named and referenced in a readme.

Please double-check file naming and referencing.

The core requests from #550...
```
- Please remove the "female genius" entry.

- Please reformat this PR to conform to our repository format. We update
the folder README's to link to the files and add a simple description.

Example...
https://github.com/papers-we-love/papers-we-love/blob/master/machine_learning/README.md

- Reconsider the filenames. Please use - or _ instead of the . separator
(except for file extensions). Do not add YouTube links as files, link
them from the README.
```

Remove this:
- mathematics/moon duchin on female genius.pdf

Fix naming of these files:
- data_compression/see.machine.learning
- machine_learning/curt.mac.mullen.renormalisation.video.url
- mathematics/ardila.tilings.0501170.pdf
- mathematics/daniel litt. graph isomorphism and representation theory. graphs-sl2.pdf
- mathematics/triality.in.so(4,4).characteristic.classes.d4.g2.singularities.1311.0507.pdf
- mathematics/whatis a young tableau? alexander yong.pdf

Please double-check the formatting of `machine_learning/README.md`.

Also, please revise `mathematics/README.md` for tone -- to be more neutral. If this is an uncomfortable request, delegate that to me, or understand that this will be rewritten.

Language like this is presumptuous and potentially insulting...
```
This <10-page paper also uses `𝔰𝔩₂(ℂ)`, a simple mathematical object
you haven’t heard of, but which is a nice lead-in to an area of real
mathematics—rep theory—that (1) contains actual insights (1a) that
you aren’t using (2) is simple (3) isn’t pretentious.
```

**Comment by NewAlexandria** [comment]
I think most of this is done, but I did copy the comment verbatim, so a few edits will be needed there.  I corrected most of the paper names.  Excluded that one book review. Added README entries in normal repo form.  

I did not confirm PDF copyrights.

**Comment by hakutsuru** [comment]
> I think most of this is done, but I did copy the comment verbatim

I am not blaming you, but this is a mess.

I see 19 binary files, and only 16 "scroll" references added -- via cursory review.

Unfortunately, cursory review is not sufficient here, it will take an *in-depth review* to ensure this pull request does not make things worse.

> Excluded that one book review

Yet the file still exists in the pull request.

****

Before we put significant work into getting this merged, we have to agree on reality. I closed the original pull request after four months of inactivity.

There are three ways forward:
- This falls off the radar again, and we close it again.
- You request I fix it, and offer to assist where possible.
- Someone else fixes it.

No matter what, this will pass the standards of the project. Darren, I or another member will remove anything which gets merged without having been revised to our standards.

**Comment by NewAlexandria** [comment]
Ugh, you’re right.  I thought with the commits for a while on this and to try to preserve them off automatically, and in the end had to just block them off one by one.  Somewhere in that surgery I still missed bits.  I’ll fix it though.  

(looking through the actual committee, I somehow misread the terminal, and now see the non of my name changes nor file deletes were preserved. Very sad.)

Also, since I’m not OP, I’m less opinionated about which of these are deeply worth it. Obviously the EAT chapter on Sheaves is a classic, etc. 

May take me until later in the week to find time again. Sorry for the false start.

**Comment by hakutsuru** [comment]
Thanks for taking this on, after your next update, I will review more carefully.

> less opinionated about which of these are deeply worth it

Please skip/remove anything which is not obviously worthwhile to you.

This is a starting point for adding relevant math to the collection, so we should focus on material which is easy to justify.

**Comment by NewAlexandria** [comment]
@hakutsuru I've retrieved the commits that had updated the paper titles to be correct.  I also came up with better wording for the READMEs (which I didn't do originally and should have been mindful of), and I also removed a few papers that I didn't think I could as easily speak for. 

What I'd like feedback on: 

* since there are several papers added, do you want each to be in the PR description in the typical PR format, or do you want to read the rational for inclusion in the README itself?
* Some of the papers, while good, are in the format of shorter length articles that cover an overview of a major topic in mathematics.  While that is helpful for those that are getting into the field, it is not 'a seminal paper'.   Do we want to omit these articles, despite their efficacy and giving insight into major topics?
* I did not check copyright on them all.  I cannot image that Elements of Algebraic Topology is allowed to be republished — even though just the one chapter, and even though a multitude of full-scans for the entire book are available through a google search. How would you like me / someone to handle all that?

Thanks.  Happy Thanksgiving

**Comment by hakutsuru** [comment]
Please bear with me here, this is much improved, but review can be a challenge to format -- not inclined to do line-based comments.

For hosted papers, please use relative links, see `papers-we-love/data_compression/README.md`.

For mathematics papers, please update readme format to be simple (remove link from scroll icons)...
`:scroll: [The Transcendence of pi](transcendence-of-pi.pdf) by Steve Mayer`

In the machine learning readme...
- `by Mallet` should be `by Mallat`.
- Not sure how the annotations for `Understanding Deep Convolutional Networks` and `General self-similarity` are helpful -- perhaps they could be removed.
- Annotation for `Truncation of Wavelet Matrices` is almost too informative, but could arguably help a reader interested in the topic.

In the mathematics readme...
- Descriptions should be brief and informative.
- Capitalization of the link should match the paper.
- For `Tilings`, classifying readers as programmers or not should be approached with utmost care. Perhaps revise to "Covers a broad swath of the topic of analysis of tiling, and related strategies". 
- For `graph isomorphism and representation theory`, as a stylistic note "<10 page paper" reads better as _short paper_. Note sure the conversational tone is helping here.
- For `Conway's ZIP proof`, this must be shortened. Most of this info would belong in the pull request, and not in the readme. The last line seems the most worthwhile.
- For `packing of spheres`, this needs a cogent statement. Nothing would be better than a list.
- For `some underlying geometric notions`, suggestion -- "High-Level survey which relates disparate topics, e.g. Platonic solids (A-D-E), Milnor’s exceptional fibre, and algebra."
- For `what is a young tableaux?`, eliminate empty language, e.g. "Young Tableau appear in  combinatoric problems, representation theory, and the calculus of Grassmannians."

We must treat copyrights with respect. Naturally, if we are alerted to anything which should not be distributed, we would remove the material. But those cases should be rare, and primarily due to a lack of notice (whereas including material which would obviously be challenged is disrespectful).

If there is an obvious existing copyright or restriction on a paper, we must not host the paper -- though we could reference it via link

**Hosting seems fine**
- machine_learning/General-self-similarity--an-overview.pdf 
- machine_learning/Understanding-Deep-Convolutional-Networks.pdf
- mathematics/from-dominoes-to-hexagons.pdf
- mathematics/graph-isomorphism-and-representation-theory.pdf
- mathematics/intro-to-tropical-algebraic-geometry.pdf
- mathematics/tilings.pdf

**Convert to link or remove**
- machine_learning/Truncation-of-Wavelet-Matrices--Edge-Effects-and-Reduction-of-Topological-Control.pdf [Elsevier, with reprint fee]
- mathematics/conways-zip-proof.pdf [American Math Monthly]
- mathematics/elements-of-algebraic-topology-ch9-sheaves.pdf [CRC Press]
- mathematics/packing-of-spheres.pdf [Scientific American]
- mathematics/some-underlying-geometric-notions.pdf [Hatcher "Algebraic topology", Cambridge University Press]
- mathematics/topology-of-numbers--hatcher.pdf [https://pi.math.cornell.edu/~hatcher/TN/TNbook.pdf]
- mathematics/what-is-a-young-tableau.pdf [https://www.ams.org/notices/200702/whatis-yong.pdf]

****

> do you want each to be in the PR description in the typical PR format, or do you want to read the rational for inclusion in the README itself?

Either way makes sense, and seems applicable. The machine learning readme seems well done, so perhaps that is a good model.

A brief description in the readme of what is to be gained by reading the paper, or what it represents, seems beneficial -- since few readers will see the pull request.

But personal reasons and advocacy for a paper are best kept in the pull request.

> Some of the papers, while good, are in the format of shorter length articles that cover an overview of a major topic in mathematics... Do we want to omit these articles, despite their efficacy and giving insight into major topics?

While seminal papers are ideal, the mathematics topic is greenfield territory -- including overview reading seems a benefit.

If others contribute, the topic can be made more sophisticated, comprehensive and cohesive.

> cannot image that Elements of Algebraic Topology is allowed to be republished... How would you like me / someone to handle all that?

Include a link reference for anything which seems problematic, or omit entirely.

**Comment by NewAlexandria** [comment]
OK @hakutsuru 
* I fixed relative links, and `:scroll:` links
* the annotations you suggest being removed I tried to improve, instead. 
* did this for ML and Math sections

Merry Christmas, all

**Comment by hakutsuru** [comment]
Thanks. Looks like there are hosted icons which should be removed. I will handle clean up.

Great work, @NewAlexandria.

**Comment by NewAlexandria** [comment]
Thanks!

**Pull request merged**
