### PR TITLE
adds gothenburg chapter

### PR DESCRIPTION
**Pull request by nachivpn**
We had our first meetup on the 1st of December. 

All media from the event can be found here: https://www.meetup.com/Papers-We-Love-Gothenburg/events/235666159/

### CODE REVIEW

**Comment by hakutsuru** [comment]
+1

If you ever have media (video, slides, etc) to share via the paperswelove.org site, let us know.

**Comment by nachivpn** [comment]
Sure!

**Comment by hakutsuru** [comment]
The website is driven by a different repo -- https://github.com/papers-we-love/papers-we-love.github.io

Could you also add yourself there, and the team will update the site?

**Comment by nachivpn** [comment]
Will do!

**Pull request merged**
