### PR TITLE
Add Crash-Only Software papers

### PR DESCRIPTION
**Pull request by sdboyer**
This adds a couple papers, primarily by [George Candea](http://people.epfl.ch/george.candea). I'll be presenting the first one, Crash-Only Software at the [http://www.meetup.com/papers-we-love-Detroit/events/221358596/](inaugural PWL Detroit meeting). Hopefully I'll find a venue and a camera, and then that'll happen soon :)

a few things:

* I've no idea about usenix and licensing, so i'm not sure if it's OK to keep them here. FWIW the front page does say, "Permission is granted for noncommercial reproduction of the work for educational or research purposes."
* I've included the microreboot paper as well because it's really a logical continuation of the same idea, though I'm not really planning to touch on it in my presentation. It's also the more heavily cited paper. I'm fine to pull it out, though, if that's the preference...
* Maybe there's a better directory to put these under already, and I'm totally fine if so...but I couldn't really pick one out.

### CODE REVIEW

**Comment by sdboyer** [comment]
oh right, the justification.

i don't think it's fair to say that this paper necessarily spawned a whole new field - though it did coin a useful term, "crash-only software," that seems to have become a standard term for software with these properties.

the reason i really like it and am presenting on it is because my experience building software with crash-only properties strongly led me right back to something reminiscent of functional reactive programming - though not actually b/c my thing is written in Go - immutability, and a shared append-only log design that will ultimately be amenable to being made distributed. while crash-only designs can (...probably? i'm sure...) be achieved in other ways, these ways fit like a glove.

to that end, i've found that maintaining a crash-only orientation provides a simple invariant that leads people to naturally tumble down the rabbit hole of all these topics - all of which are the sorts of things PWL professes great interest in.

most importantly, though, this paper/presentation provides an opportunity to demonstrate how [DJ Khaled](https://soundcloud.com/user602350/01-all-i-do-is-win-feat-t-pain) is the grand poobah of devops and computer science.

**Comment by zeeshanlakhani** [comment]
@sdboyer thank you for these. I'd say that for `Crash-Only Software` that we just include the link and not the binary... to be safe. Can you make that update? Also, should the category be `crash-only software` as well or is the official tag just `crash-only`? Thank you for the explanation too :).

**Comment by sdboyer** [comment]
you bet! sorry for slow response. new commit removes the docs.

i'm not really sure about the tag, but i think it's probably right as `crash-only`, as i've seen this concept variously referred to as "crash only software", "crash only architecture", "crash only approach", etc.

**Comment by zeeshanlakhani** [comment]
@sdboyer just one more thing... mind rebasing this into one commit? Then I'll merge!

**Comment by sdboyer** [comment]
squashed, merge away :)

**Pull request merged**
