### PR TITLE
Added Elm language thesis

### PR DESCRIPTION
**Pull request by olegakbarov**

### CODE REVIEW

**Comment by DarrenN** [comment]
Should we cross-link with https://github.com/papers-we-love/papers-we-love/blob/47ae00c021e2abf5e41868512663e8e1cf2cbc57/functional_reactive_programming/README.md ?

**Comment by olegakbarov** [comment]
Yeah i guess so.

**Comment by zeeshanlakhani** [comment]
@olegakbarov up for making the update w/ the cross-link?

**Comment by DarrenN** [comment]
Going to close this due to inactivity soon.

**Comment by DarrenN** [comment]
Closed due to inactivity. Please re-open if the outstanding issues are addressed.

**Pull request closed without merging**
