### PR TITLE
Move languages into languages dir. Move 'tdd' dir into testing

### PR DESCRIPTION
**Pull request by joereynolds**
I got round to it sooner than I thought (cloning was quicker than expected).
Any thoughts/improvements?

### CODE REVIEW

**Comment by joereynolds** [comment]
Whilst I'm here, how about another directory that we put paradigms into?
i.e.
paradigms/object_oriented_programming/readme.md
paradigms/functional_programmg/readme.md
paradigms/logic_programming/readme.md

That would further reduce the bloat at the top level. Not sure if paradigms is the right word though...?

**Comment by NewAlexandria** [comment]
I think this raises the discussion whether we should treat concepts as being language-agnostic, or if concepts are more-dependent on language, and thus are better to be categorized that way.

I think an earlier PR discussed the idea of indices — `.md` files with a list of content.  This is a solution to having language-specific paper indices.  That 'index.md' idea was also nixed, if I recall, because it would fall out-of-maintenance and look poorly.  

I'm in the language-agnostic camp.  It would be great to hear counter-points or other schemes.

**Comment by joereynolds** [comment]
I agree with your points about maintability but at the moment, seeing it for the first time yesterday, the directory structure is too flat.

For instance, there are these directories
```clustering_algorithms```
```sublinear_algorithms```
```clustering_algorithms```

There very name states they should be in an ```algorithms``` directory. The crucial part of this, is making sure the names convey something and that the files definitely belong in the directory.

If we name the directories correctly, it will be much easier to find what you want

**Comment by joereynolds** [comment]
What work needs to be done on this to get it merged? Are there particular decisions in this PR that you don't agree with?

**Comment by hakutsuru** [comment]
Language subdirectories seems an obvious idea.

And paradigms, too. This introduces issues of cross-referencing.

There may be languages that are synonymous with a paradigm, and then, the content of the paper should dictate where the original be found (if an artifact), but then referenced in other places (such as forth and stack_oriented_programming).

**Comment by joereynolds** [comment]
Cross referencing may be a problem, but then again it may not, at the moment, I can't see any problems and I don't see the benefit of holding back on doing something just because it *may* at some point be a problem

**Comment by hakutsuru** [comment]
+1

****

I do not see a "problem", and I am also in the "language-agnostic camp".

The crew has been busy with pwlconf, but I was hoping to entice others to comment. This seems like an improvement, so let's carry on. Thanks.

**Comment by zeeshanlakhani** [comment]
Agreed, def. an improvement, thank you @joereynolds!

**Pull request merged**
