### PR TITLE
Add a link to Fermat's Library

### PR DESCRIPTION
**Pull request by 3rdman**
Fermat's Library is a weekly paper that ends up being annotated by the community-at-large.

### CODE REVIEW

**Comment by hakutsuru** [comment]
+1 new resource and white space cleanup

**Comment by deltamualpha** [comment]
Is there a way to link directly to the CS topic on the Fermat homepage, since that's our area of focus?

**Comment by 3rdman** [comment]
Good question. I  will check and resubmit tomorrow if there is a direct link.

**Comment by zeeshanlakhani** [comment]
Any update on the direct link @3rdman ?

**Comment by 3rdman** [comment]
Hey @zeeshanlakhani, my apologies for not getting back to this sooner as I thought I would.

A direct link doesn't appear to be present.

Let's close this out and I'll see about reaching out to them for a direct link after the Thanksgiving break here.

**Pull request closed without merging**
