### PR TITLE
Papers We Love Bucharest added

### PR DESCRIPTION
**Pull request by eduardtm**

### CODE REVIEW

**Comment by DarrenN** [comment]
@eduardtm - did you have meetup in September? Any planned for October?

**Comment by eduardtm** [comment]
@DarrenN - there wasn't one in September, next Monday is our October meetup http://www.meetup.com/papers-we-love-bucharest/events/225905619/ .

**Comment by DarrenN** [comment]
@eduardtm okay - can you fix this up so its merge ready?

Thanks

**Comment by eduardtm** [comment]
@DarrenN it should be merge ready now

**Comment by DarrenN** [comment]
:+1:

**Pull request merged**
