### PR TITLE
Add link to article by Marvin Minsky

### PR DESCRIPTION
**Pull request by AkshayIyer12**
## Paper Title: Why programming is a good medium for expressing poorly understood and sloppily formulated ideas.
Title originally by Marvin Minsky, 1967 in Design and Planning

### Reasons for including paper
* It discusses about programming as a linguistic phenomenon like mathematical expressions.
* It also describes programming has two aspects poetry and prose using Lisp.
* It also discusses how in programs we express knowledge of world, express models of possible structures.
-
-
-

### CODE REVIEW

**Comment by DarrenN** [comment]
@AkshayIyer12 thanks for the submission! 

Please convert the title of the link in the README from "WHY PROGRAMMING IS A GOOD MEDIUM FOR EXPRESSING POORLY UNDERSTOOD AND SLOPPILY-FORMULATED IDEAS" to proper title case. I understand that it's all caps in the article, but I suspect this is an artifact from the original formatting.

Thanks.

**Comment by AkshayIyer12** [comment]
@DarrenN I have updated it. Thanks :+1:

**Comment by DarrenN** [comment]
Thank you!

**Comment by buzzthegreat** [comment]
Please stop sending me emails

**Pull request merged**
