### PR TITLE
Adding Madrid chapter

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
First meetup will be held February 12th. Not sure if I have to wait until it is actually held so I am sending the pull now :)

**Comment by DarrenN** [comment]
Thanks for making the PR @migue - let us know when you've had the meetup (and I hope it goes well!) and we'll merge the PR.

**Comment by migue** [comment]
Hey @DarrenN ,

We've already hold our first meetup (http://www.meetup.com/Papers-We-Love-Madrid/events/219836948/)

There is a blog post with the "text" of the talk http://videlalvaro.github.io/2015/02/programming-myths.html and the slides are here https://speakerdeck.com/old_sound/harmful-gotos-premature-optimizations-and-programming-myths-are-the-root-of-all-evil

Thank you very much guys!!

**Comment by DarrenN** [comment]
Very cool @migue - we will get you added to the list.

Also, you can add yourself to http://paperswelove.org with a PR: https://github.com/papers-we-love/papers-we-love.github.io#adding-a-chapter

**Comment by migue** [comment]
Thank you guys!! I will take a look to it and will make the pull request as you already noted!!

**Comment by zeeshanlakhani** [comment]
@migue also, what's a good email to reach you at? We'll add you to our PWL Organizers' Google Group.

**Comment by zeeshanlakhani** [comment]
I've also added the slides to our SpeakerDeck -> https://speakerdeck.com/paperswelove.

**Comment by migue** [comment]
miguelinlas3 at gmail dot com

**Pull request merged**
