### PR TITLE
New chapter in Paris, France

### PR DESCRIPTION
**Pull request by fbiville**
We successfully held our [first session](http://www.meetup.com/Papers-We-Love-Paris/) on 3rd of June.
More sessions to come!

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
:+1: @fbiville what's a good email address to reach you at? I'll add you to our Google Group.

**Comment by fbiville** [comment]
@firstname@ DOT @lastname@ AT gmail ;-)

**Comment by hakutsuru** [comment]
@zeeshanlakhani: Did you forget to ask about video?

**Comment by zeeshanlakhani** [comment]
I asked on twitter awhile back @hakutsuru. Correct me if I'm wrong @fbiville, but you didn't shoot video yet, right? If you do eventually, we'll add you to the YT group ;).

**Comment by fbiville** [comment]
@zeeshanlakhani that's right, so far, we haven't found anyone up to the task.
Recording may happen with some hosts but this isn't always guaranteed.

**Pull request merged**
