### PR TITLE
Creating mathematics Folder and adding transcendence of pi paper

### PR DESCRIPTION
**Pull request by vaibhawvipul**
### Reasons for including paper

- Lays out all proofs of transcendence of pi 
- Also includes a proof showing transcendence of e
- Helpful to all undergraduates and people who follow mathematics

### CODE REVIEW

**Comment by DarrenN** [comment]
@vaibhawvipul thanks for submitting this paper. Please add a README for the new folder you're proposing. We have some information here: https://github.com/papers-we-love/papers-we-love/blob/master/.github/CONTRIBUTING.md and example README: https://github.com/papers-we-love/papers-we-love/blob/master/artificial_intelligence/README.md

Thanks!

**Comment by vaibhawvipul** [comment]
added README.md

**Comment by DarrenN** [comment]
Thanks @vaibhawvipul can you remove mathematics/transcedence-of-pi.pdf ? Otherwise both will be merged into the repo.

**Comment by vaibhawvipul** [comment]
I want both to be merged in the repo! Do you want me to do separate commits for each?

**Comment by DarrenN** [comment]
@vaibhawvipul are they different papers? Why are the filenames (typo aside) the same?

**Comment by vaibhawvipul** [comment]
They are same. I corrected the filename(typo) in a commit.

**Comment by DarrenN** [comment]
I don't understand why you are including the same paper twice, is there some difference between the two?

**Comment by lrascao** [comment]
@vaibhawvipul you probably need to rebase your branch onto upstream's master

**Comment by vaibhawvipul** [comment]
Really sorry... there was some error. I removed that duplicate file. Apology for the trouble

**Pull request merged**
