### PR TITLE
mathematics papers

### PR DESCRIPTION
**Pull request by isomorphisms**
There’s not much representation from the mathematics department in your papers list.

Maybe 2 of these could be “directly” useful. But, per twitter.com/fchollet, CS researchers need to read outside their speciality more. Broaden your mind a bit, it will decrease the amount you feel is publication-worthy—and increase the signal:noise ratio for everyone.

Additionally you might even find yourself entertained or (at least a bit!) enlightened/changed.

All of these papers are readable and jargon-free. Most have pictures. Most are short (under 10 pages).

This isn’t to say that digesting 2 pages which are actually filled with ideas is quick or easy. Most of the AMS “What is…?” two-pagers take me week to years to read. I’m posting these because I can nearly guarantee that they *won’t be a waste of your time*.

### CODE REVIEW

**Comment by DarrenN** [comment]
Thanks for contributing. There are some small tweaks to this PR that would need to happen before we can merge.

1. Please remove the "female genius" entry.
1. Please reformat this PR to conform to our repository format. We update the folder README's to link to the files and add a simple description. [Example](https://github.com/papers-we-love/papers-we-love/blob/master/machine_learning/README.md)
1. Reconsider the filenames. Please use `-` or `_` instead of the `.` separator (except for file extensions). Do not add YouTube links as files, link them from the README.

Thanks.

**Comment by isomorphisms** [comment]
What’s wrong with the female genius paper?

**Comment by isomorphisms** [comment]
I’ll fix 2 and 3.

**Comment by maximveksler** [comment]
> What’s wrong with the female genius paper?

I wouldn't feel comfortable with `papers-we-love` to be used as platform for agenda spreading.

This is not a scientific paper it's a personal opinion statement. It was never published anywhere and was never peer reviewed. It presents a biased social politics view, under the postmodernist narrative. A minority world view. It is written by a known feminist activist. I would not consider well for it to be included in the index.

**Comment by NewAlexandria** [comment]
Regardless of each persons ideological preferences, we can all agree that the paper is not peer reviewed.  Including a paper that has such an objectively lower quality standard (compared to the rest of PWL), and on such an important contemporary topic, might actually lower the perceive value and receipt of this paper and its topic.  I think that is the risk of including this essay/review.

(@isomorphisms  It's not even source material, it's a oped summary of the books "Female Genius")

**Comment by hakutsuru** [comment]
Closing this due to lack of activity.

Anyone is free to resubmit this content, with the modifications requested by the organization.

**Pull request closed without merging**
