### PR TITLE
Added Synthical (https://synthical.com)

### PR DESCRIPTION
**Pull request by mixeden**

### CODE REVIEW

**Comment by DarrenN** [comment]
👋🏽 Closing this, as it seems you're making a lot of commits across many, many repos (many of which you created) dropping this link. Honestly seems like an SEO move.

**Comment by mixeden** [comment]
No, I am committing this link to awesome lists related to ML and DS (you can check out, all the repos I'm committing to are forks). This is not for SEO, this is for discoverability of the platform in general.

**Comment by mixeden** [comment]
I am sorry if this seemed SEO-ish, and I didn't think it would seem odd to anyone if I submitted it to multiple repositories (because... why not?)

**Comment by deltamualpha** [comment]
Ok, so it's not SEO, it's just marketing. Thanks, but no thanks.

**Comment by mixeden** [comment]
Do you think rejecting or approving PRs based on whether they are marketing-related (rather than whether they are useful to users of a given repo) is a good strategy?

**Comment by deltamualpha** [comment]
Yes. People who get value from our repository find that value because we curate the content, as opposed to just adding everything someone suggests.

**Pull request closed without merging**
