### PR TITLE
Add Google Macaroons paper.

### PR DESCRIPTION
**Pull request by wesc**
Simple and elegant improvement over standard cookies. Solves some useful real world problems (third party authentication, sharing links), came out of Google research, is a great meld of theory and practice.

### CODE REVIEW

**Comment by NewAlexandria** [comment]
Should be added to [the security section's README](https://github.com/papers-we-love/papers-we-love/tree/master/security), preferably in a [complete citation format](https://github.com/papers-we-love/papers-we-love/issues/257#issuecomment-68262229).

**Comment by zeeshanlakhani** [comment]
Great stuff @wesc. We haven't made the citation formatting explicit on our contribution README, but will shortly (checking-in w/ @jeremyheiler on that). 

You can keep this binary, but also add the link and your comment above to the *security* readme. Add a :scroll: in front of the link to show that it's also in the repo, e.g. some of the examples [here](https://github.com/papers-we-love/papers-we-love/tree/master/distributed_systems).

**Comment by wesc** [comment]
Do I link directly to the pdf (http://research.google.com/pubs/archive/41892.pdf) or to the abstract page (http://research.google.com/pubs/pub41892.html)?

Also, I renamed the pdf to match the title. That's ok I assume?

**Comment by zeeshanlakhani** [comment]
@wesc, I'd link to the direct pdf. Matching the title is the right way to go.

**Comment by wesc** [comment]
Ok updated with link and :scroll:.

**Comment by zeeshanlakhani** [comment]
:+1: @wesc. @NewAlexandria, we're working on the citation format for stuff going forward. More info to come on that.

**Pull request merged**
