### PR TITLE
Adding projectional editor paper, presented in Seattle papers we love in May 2017.

### PR DESCRIPTION
**Pull request by Khalian**
### Reasons for including paper : It was presented in Seattle papers we love May 2017. 

-
-
-

### CODE REVIEW

**Comment by DarrenN** [comment]
@Khalian convert this into a list and I'll get it merged. 

* entry
* entry
* etc...

**Comment by Khalian** [comment]
@DarrenN I am not sure I follow.

**Comment by DarrenN** [comment]
@Khalian we usually put papers in a list format. Example: https://github.com/papers-we-love/papers-we-love/tree/master/audio_comp_sci

**Comment by Khalian** [comment]
Done.

**Pull request merged**
