### PR TITLE
Update to all READMEs for hosted content

### PR DESCRIPTION
**Pull request by NewAlexandria**
Per #91, this normalization is my afternoon gift to the Papers We Love community.

Update also reorganizes the so-called 'historical papers'... which really fit better into existing folders.

Suggestions welcome

### CODE REVIEW

**Comment by NewAlexandria** [comment]
After doing this update, I felt like the Distributed Systems folder is not well organized.  I'd guess half of the hosted papers are in the distributed_systems folder.  Some look like they are better suited as networking topic (e.g. maybe the Tor paper).

So, overall, I'd like to suggest reorganizing this folder.  We can relocate papers and make links out to where they are located, perhaps in an 'appendix' section of the README.

**Comment by jeremyheiler** [comment]
Thank you @NewAlexandria; this is great!

:+1:

**Comment by zeeshanlakhani** [comment]
@NewAlexandria so many thanks for this. :clap: forever!

**Comment by NewAlexandria** [comment]
:construction_worker: :wrench: :sweat_drops:

**Pull request merged**
