### PR TITLE
Added the Diffie Hellman paper

### PR DESCRIPTION
**Pull request by kc1212**

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
@kc1212 thank you for this. Can you say a little bit about why you think this paper should be included in the repo?

**Comment by kc1212** [comment]
This is the famous Diffie-Hellman paper that described a practical key exchange algorithm for the first time. It is now known as the [Diffie-Hellman key exchange](https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange). Many forms of secure communication today rely on Diffie-Hellman key exchange (or its [variants](https://en.wikipedia.org/wiki/Elliptic_curve_Diffie%E2%80%93Hellman)) to establish a secure channel.

**Comment by webhat** [comment]
:+1:

**Comment by DarrenN** [comment]
:+1: foundational crypto paper

**Comment by zeeshanlakhani** [comment]
:+1:

**Pull request merged**
