### PR TITLE
Added script to download all (pdf) papers locally

### PR DESCRIPTION
**Pull request by christoshadjiaslanis**

### CODE REVIEW

**Comment by DarrenN** [comment]
Thanks for submitting this shell script. Some suggestions:

- Maybe we should move this to a `tools` or `scripts` directory
- We should probably give it a README or comprehensive comment block explaining what it does, how to use it and that it requires `wget`.

**Comment by christoshadjiaslanis** [comment]
All done. Feel free to squash and merge.

**Comment by hakutsuru** [comment]
This is close, you could fix the following issues, or request we merge and handle fixes ourselves. I appreciate your cooperation with previous requests...

****

macOS Mojave `xargs` does not support `--no-run-if-empty`...
```
 ~/Repos-volunteer/papers-we-love/papers-we-love/networks (master)$ ls | cat *.md 2> /dev/null | egrep -o 'https?://[^ ]+' | grep 'pdf' | tr -d ')' | xargs --no-run-if-empty wget --no-clobber --quiet --timeout=5 --tries=2
xargs: illegal option -- -
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
```

*Readme* is odd. The file should start with a header and orientation (e.g. scripts for working with repo content), and then a section devoted to `download_all`.

The description of `download_all` does not explain that it downloads PDFs referenced by URL. The value and intent of this tool should be clear from the docs. We must not require the audience read the script to understand why it is included.

**Comment by kuskmen** [comment]
Also wouldn't it be more helpful if we denote which folder(area) we would like to download because I assume most of the people will be interested in only certain topics rather than everything we have.

**Comment by christoshadjiaslanis** [comment]
So -

1. Removed `xargs` dependency as `xargs` doesn't play nice across *nix.
2. Updated **README**
3. Added functionality to explicitly specify directories as @kuskmen suggested.

**Comment by hakutsuru** [comment]
If this becomes frustrating, I could fix this for you. Also, if I suggest anything incompatible, I am open to different solutions. Thanks for adding the feature requested by @kuskmen

This does not work:

`$ ./scripts/download.sh android concurrency`

(Adding enhancements to working code, which then fails our examples, is a common experience...)

****

Please fix the script logic...
```
if [[ "$#" -eq 0 ]]; then
```

As this statement is only true for the no-arguments case, I would remove it from the docs...
```
This can be run from anywhere as long as the script doesn't change location
```

Update the parsing of urls to be more specific
```
grep '\.pdf'
```

This will avoid matching an odd download link in `concurrency`:
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.108.1302&rep=rep1&type=pdf

Such downloads are oddly named, and may confuse some users.

**Comment by hakutsuru** [comment]
I know back-and-forth requests can seem punitive, so I would like to add some context.

@DarrenN asked privately for additional review of this work on slack (#pwlnycgroup). In our private channel, there are various engineers with ops/devops/unix experience. While working with Darren years ago, I spent a lot of time writing shell scripts -- so I appreciate the utility and challenge of automation scripting.

**Comment by christoshadjiaslanis** [comment]
Sure - to the contrary thank you for taking the time.  (Good catch on the logic I missed that one completely). 

I have implemented your suggestions.

As you can probably tell I don't have much experience in shell scripting. The lack of `xargs`  has made this slightly slower. I realise performance is not a hard requirement but if anyone from your team is up to speeding this up then by all means.

**Comment by hakutsuru** [comment]
We can always revisit this later if performance become frustrating.

Thank you for contributing. I am sure readers will be delighted with this automation.

**Pull request merged**
