### PR TITLE
Add Medellin to the list of chapters

### PR DESCRIPTION
**Pull request by castillobg**
Removed dangling space too :)

### CODE REVIEW

**Comment by DarrenN** [comment]
@castillobg - have you had your first meetup yet?

**Comment by castillobg** [comment]
@DarrenN, nope. But it's well on its way :D Can it be added only when the first meetup's done?

**Comment by DarrenN** [comment]
@castillobg - indeed, we only add chapters after their first meetup.

**Comment by castillobg** [comment]
@DarrenN Ahhh, got it. Closing this for now, then :)

**Pull request closed without merging**
