### PR TITLE
Updated tutorial link (was 404ing)

### PR DESCRIPTION
**Pull request by pemcconnell**

### CODE REVIEW

**Comment by DarrenN** [comment]
@pemcconnell is this the same paper? http://luthuli.cs.uiuc.edu/~daf/courses/Signals%20AI/Papers/HMMs/0.pdf

**Comment by pemcconnell** [comment]
Yeah looks like it is - nice find. Updated PR to suit

**Comment by DarrenN** [comment]
:+1:

**Comment by zeeshanlakhani** [comment]
:+1:

**Pull request merged**
