### PR TITLE
Recently added

### PR DESCRIPTION
**Pull request by joereynolds**
Adds a very rough recently_added markdown file.

This definitely needs some work as there's no automated way to do this (They have to run the install.sh file the first time they use this repo to create the relevant symlinks)

Thoughts?

### CODE REVIEW

**Comment by DarrenN** [comment]
Thanks for this @joereynolds - so to make this work, we would need to manually handle PRs and merges locally, not on GH?

**Comment by joereynolds** [comment]
nope, but the first time you ever use it, you'd need to run `install.sh` so that it creates the symlink from the git_hooks directory into your actual git hook directory in .git/hooks.

A hook is the only way I can think of making sure that it does it automatically, either that or a build plan/cron job but that seems like over-engineering for what is essentially a bunch of pdf's in one place.

**Comment by joereynolds** [comment]
Well, it's a bit complicated unfortunately :(

The script to create the recently-added, is a post-commit hook, but in order for that to work correctly, you need to run `install.sh` which will symlink the git_hooks/post-commit file to the actual one located in .git/hooks/post-commit

This means that if a user wants to do work entirely through github then it probably won't work.

The other idea might be to perhaps use some sort of lightweight build system that calls the git hook once it's been merged. But I can't help but feel that's over-engineering for something that is essentially a list of pdf files.

How were you going to get your Racket script to automate the process out of interest?

**Comment by DarrenN** [comment]
http://paperswelove.org is assembled with a build process on a server. We could potentially adapt that to run `git log --name-status | \grep "^A\s" | grep -v README\.md | awk '{ print $2 }' | head > recently_added.md` and push up the markdown file on a cron job.

**Comment by joereynolds** [comment]
Sounds perfect :D

**Comment by jeremyheiler** [comment]
I think we can do this with CircleCI whenever we merge into master.

**Pull request closed without merging**
