### PR TITLE
Add TDD with mutation testing (Roman & Mnich 2020)

### PR DESCRIPTION
**Pull request by walerian777**
## Paper Title
_Test-driven development with mutation testing – an experimental study_

### Paper Year
2020

### Reasons for including paper
It presents an old idea of mutation testing in a new light of extending traditional test-driven development with it. It includes results of an experiment which was conducted to check whether TDD+M is better in terms of test efficiency than traditional TDD.

### CODE REVIEW

**Comment by HonzaMac** [comment]
Cc @nicojs

**Review by hakutsuru — CHANGES_REQUESTED** [review]
@walerian777 Please remove the included PDF, and the scroll icon for the paper in the readme. Thanks.

****

We do not include materials which could violate copyright, and documents included must be clearly/arguably legal. If there is proof including this paper would not violate copyright, feel free to send this along for consideration.

**Comment by walerian777** [comment]
Hi @hakutsuru, does this qualify?
> Open Access This article is licensed under a Creative Commons Attribution 4.0 International License, which permits use, sharing, adaptation, distribution and reproduction in any medium or format, as long as you give appropriate credit to the original author(s) and the source, provide a link to the Creative Commons licence, and indicate if changes were made.

Source: https://link.springer.com/article/10.1007/s11219-020-09534-x#rightslink

**Comment by hakutsuru** [comment]
> does this qualify?
> Source: https://link.springer.com/article/10.1007/s11219-020-09534-x#rightslink

The source indicates Springer is hosting this paper legally, and clearly shows how the current pull request would violate terms of the license.

I am not aware of any similarly licensed paper currently hosted in the repo.

Allowing readers access to the paper via link is the simplest solution. Otherwise, this pull request would need to be updated to be compliant with the license, and that could require multiple rounds of review.

**Comment by walerian777** [comment]
Thanks for the explanation, I'll remove the PDF then.

**Review by hakutsuru — APPROVED** [review]

**Comment by hakutsuru** [comment]
Thanks, @walerian777

**Pull request merged**
