### PR TITLE
Add links to more garbage collection papers.

### PR DESCRIPTION
**Pull request by aturley**
I added a few things. Let me know if I did it wrong, or if there's something else I should do.

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
Great stuff @aturley! The only issue is that the ftp link for `The Lisp II Garbage Collector` is not linking correctly on preview. Is gh handling this poorly?

**Comment by aturley** [comment]
God damn it. https://github.com/jekyll/jekyll/issues/373

Using raw HTML anchor tags doesn't work either. Should I make a local copy and submit a new PR?

**Comment by aturley** [comment]
Accidentally closed, so re-opening.

**Comment by zeeshanlakhani** [comment]
@aturley yeah, a local copy should work.

**Comment by aturley** [comment]
OK, closing out for real this time, new PR in the works.

**Pull request closed without merging**
