### PR TITLE
add awesome_bot for external link checking #360

### PR DESCRIPTION
**Pull request by zerg000000**
This is an attempt to add [awesome_bot](https://github.com/dkhamsing/awesome_bot) for checking external link. you can check the expected result here

https://travis-ci.org/zerg000000/papers-we-love

Please let me know if we could add more integration like post the checking result to Slack.

After adding the `.travis.yml`, the repo owner should enable the travis integration by following steps

* First go to https://travis-ci.org/ and sign in with your GitHub account.

* In the upper right corner click on your name (or choose Accounts) to open your Travis-ci profile.
You'll be presented with the list of your GitHub projects (only the ones where you have administrative authority)

* Toggle the switch on one of your projects and then click on little wrench icon to open the project's Service Hooks page on GitHub. To get to the same place from your GitHub project, go to Settings > Service Hooks.

* On the Service Hooks page scroll down to Travis and you'll notice that the hook is already activated. Click on "Travis".

* Click on Test Hook.
You'll soon (depending on the availability of a Travis worker and the size of your project) get an e-mail telling you that your project build has failed (unless you're on Ruby and you're lucky as hell). I don't know what kind of projects you run there, but this is not OK, my friend.

* Now, completely ignoring my previous comment, open the root of your GitHub project and create a new file named .travis.yml.
That's the file that will contain your Travis configuration for the repo. YML extension stands for YAML (YAML Ain't Markup Language), which is basically a specification for data exchange format, similar to JSON.

* According to the programming language of your project, fill in the Travis settings in your newly created .travis.yml file. Use Travis getting started documentation to find default settings for your language.

Reference From
https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo

### CODE REVIEW

**Comment by deltamualpha** [comment]
The output look very noisy, and do we really want to have travis pulling PDFs from all over the web on every commit? Seems very rude to the hosts of those papers.

**Comment by zerg000000** [comment]
The awesome_bot have data output could be formatted as any good looking markdown or html or pdf or whatever if needed.

Example
https://cloud.githubusercontent.com/assets/4723115/17375716/0cdd37cc-5967-11e6-8ae3-829060a786dc.png

Thanks for pointing out the pulling pdf issue . But travis checking links should have no different than doing manual link checking? If the bandwidth or workload is the issue, the commit frequency of papers-we-love is not high enough to generate pressure to paper's hosting.

Reference
https://github.com/papers-we-love/papers-we-love/graphs/commit-activity

If it is really the case, travis build could be trigger manually instead of trigger by commit.

**Comment by hakutsuru** [comment]
@deltamualpha -- Great instincts. I thought, hmmm, I would be using `head` (not `get`) for something like this, so I looked at *awesome_bot*...

And it seems that *awesome_bot* is only using `head` --
https://github.com/dkhamsing/awesome_bot/search?utf8=✓&q=net_status&type=

Could you confirm this? Do you have any other concerns?

**Comment by hakutsuru** [comment]
This is about an open issue ("External paper links that now 404") -- https://github.com/papers-we-love/papers-we-love/issues/360

Actually, I have a concern -- **travis**. (@zerg000000, thanks for the great write-up.)

Given: Link checking is a good idea...

If we are not using continuous-integration (CI) already, should we adopt travis? Or should we consider alternatives? We have other tooling working (or in development), so I wonder if it would make sense to consolidate on a platform.

@DarrenN -- Do we have a grand-ish plan? You are probably in the best position to know if we will/should be using CI, or if our tools will need to run via separate services. Perhaps *awesome_bot* analysis could be added to our other automation scripts.

If we want to avoid indecision holding us back, I am down with *travis*. But without a compelling reason otherwise, I want it's permissions on the repo to be *read-only*.

As zerg000000 stated, we should also consider how the results are published -- so that issues are visible and resolved regularly (with little friction).

**Comment by zerg000000** [comment]
@hakutsuru 
Thanks you for looking into the code. Now, the download issue become clearer.

We could have many solutions for CI part, which will have the same outcome.
`CircleCI`, `Travis` are both Great and Free solutions for Open source project.

If you prefer self-hosting, `Drone` would be great and could create same output, But need extra effort for setup. 

And actually, using a cron job to run `awesome_bot` script could do the same thing. Adapting CI solution is not mandatory.

**Comment by DarrenN** [comment]
Hi everyone - 

Sorry for the delay in jumping into the thread, but life happens.

**To give you some background**:, PWL currently has a build server that publishes http://paperswelove.org - its a Linode that runs various `cron` jobs. We currently have an experimental service running that looks at all the paper links within the READMEs and attempts to harvest metadata on them from Semantic Scholar. You can access this metadata in the [nautilus.db](https://github.com/papers-we-love/papers-we-love/blob/master/nautilus.db) file within the repo (SQLite3). Currently we do not check to see if the links themselves are valid, but this could be added pretty easily. I'm in the middle of re-architecting this service with the hopes of generating better metadata on our papers in general. The goal is to start generating JSON files for each directory and later on possibly generating the README's from this JSON. 

**TravisCI**: I'm not opposed to using Travis to do some work, as I have a fair amount of experience using it for build tasks and automated testing. However I am a little sketchy about having Travis manipulate the repo directly. Currently our build server does do this using an SSH deploy key I have setup. I would need to have a better idea of what we're trying to do.

**Comment by hakutsuru** [comment]
So we could use TravisCI or the build server.

And publish the results of a link check as a github comment on the merged pull request or on an open issue (do *not* allow TravisCI to update repo itself, but allow it to modify project as required). Or we could do something else...

There are two questions:
- where should we add the scan job
- where do the results get posted

There are pros and cons:
- comments on the pull request... people would have to check these, and adding a hook to make it a blocker adds too much friction.
- updating an existing issue... such an issue gets long, and we would have to periodically shift to a new one to avoid frustration.
- creating a new issue... could be better than long-lived issues.
- email... easily ignored, and not open to entire community.
- post to slack... hmmm?

**Comment by jmarkinman** [comment]
If it is expecting to fail, how is it so awesome when it works?

**Pull request closed without merging**
