### PR TITLE
README.md: ADD Teresina Chapter

### PR DESCRIPTION
**Pull request by Alessandro265**
* Added Teresina Chapter Link
Update README.md

### CODE REVIEW

**Comment by DarrenN** [comment]
@Alessandro265 thanks for the update. What is the `l` file that is included in the PR? It looks like a git commit log.

**Comment by Alessandro265** [comment]
That, it's a log file, sorry, I just really want you to add the chapter.

**Comment by RichardLitt** [comment]
@Alessandro265 Can you remove it from the PR, please?

**Comment by RichardLitt** [comment]
@Alessandro265; if you need help, this guide may be useful. https://github.com/RichardLitt/knowledge/blob/master/amending-a-commit-guide.md

**Pull request closed without merging**
