### PR TITLE
add the join calculus, la chapter

### PR DESCRIPTION
**Pull request by samlecuyer**
This was discussed at [the first LA meetup](http://www.meetup.com/Papers-We-Love-LA/events/220325190/)

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
@samlecuyer, can you also add the paper title/link to README of the distributed systems folder, https://github.com/papers-we-love/papers-we-love/blob/master/distributed_systems/README.md#external-papers,... like how A Note on Distributed Computing is done (w/ the :scroll:).

**Comment by samlecuyer** [comment]
@zeeshanlakhani Can you clarify?  I thought only paper's not being added to the repo get added to the readme with a :scroll:?

**Comment by zeeshanlakhani** [comment]
@samlecuyer we're trying to have them in both places now (just in case we have to remove the binary for any reason). I've also made the links in the readme link to the pdf of the paper of where it's hosted.

**Comment by samlecuyer** [comment]
@zeeshanlakhani no worries :) added it

**Comment by zeeshanlakhani** [comment]
@samlecuyer mind rebasing and we'll get this in.

**Comment by samlecuyer** [comment]
@zeeshanlakhani squashed

**Comment by zeeshanlakhani** [comment]
:+1:

**Pull request merged**
