### PR TITLE
Tchitra additions

### PR DESCRIPTION
**Pull request by NewAlexandria**
This PR adds related README changes discussed in #279 

This branch is rebased off [tchitra/master](https://github.com/tchitra/papers-we-love/commits/master) (0fa129eb45ea6a22ace850b95d12c2e0cda60948), so it should merge cleanly after #279.

Somehow, and extraneous commit (adc8701) from sdboyer made it into the branch, but may disappear after merging the dependent PR.

### CODE REVIEW

**Comment by hakutsuru** [comment]
+1

Fast Johnson-Lindenstrauss Transform paper has a link, which is great. But the pdf is still there, which is bad. I am not happy about formatting of the readme either. Those will be fixed in subsequent pull request.

**Comment by NewAlexandria** [comment]
@hakutsuru You'd prefer we leave out bibliographic citation?  I thought there was a discussion that this was preferred (or at least of interest).  I assume you'd have preferred the summary text be integrated into the same link / block as the paper's title – rather than being a separated 'abstract style' block?  Just confirming; I can't find earlier discussion about these details.

**Comment by hakutsuru** [comment]
@NewAlexandria: Thanks for putting this together. I have no opinion about the bibliographic citation, this look good to me.

The formatting that I was talking about was trivial and addressed in #314.

**Comment by NewAlexandria** [comment]
Gotcha, and thanks for that

**Pull request merged**
